spring.application.name=notification-service
server.port = 9040
server.servlet.context-path=/notifications

spring.datasource.url=jdbc:postgresql://localhost:5432/notificationDB
spring.datasource.username=postgres
spring.datasource.password=#Thanos2502
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
#This 3 introduce here to interect with api-gateway
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1