spring.application.name=posts-service
server.port=9010
server.servlet.context-path=/posts
spring.datasource.url=jdbc:postgresql://localhost:5432/postDB
spring.datasource.username=postgres
spring.datasource.password=#Thanos2502
spring.jpa.hibernate.ddl-auto=update
jwt.secretKey = asdfuasjf9a8s7fd89ihq34kljruyf98ayshcskdhfioafsuyfdcjha890sduf

#This 3 introduce here to interect with api-gateway
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1