spring.application.name=user-service
server.servlet.context-path=/users
server.port=9020
spring.datasource.url=jdbc:postgresql://localhost:5432/userDB
spring.datasource.username=postgres
spring.datasource.password=#Thanos2502
spring.jpa.hibernate.ddl-auto=update
jwt.secretKey = asdfuasjf9a8s7fd89ihq34kljruyf98ayshcskdhfioafsuyfdcjha890sduf
# Force Eureka to use localhost instead of the WSL hostname
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1